/**
 * POST /api/spotify/export
 * Creates a Spotify playlist and adds songs to it
 */

const MOOD_EMOJIS = {
    happy:'😊', sad:'😢', energetic:'💪', calm:'😌',
    romantic:'❤️', angry:'😤', nostalgic:'🌅', focus:'🎯'
};

export const config = {
    api: { bodyParser: true }
};

export default async function handler(req, res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') return res.status(200).end();
    if (req.method !== 'POST')    return res.status(405).json({ error: 'Method not allowed' });

    // Parse body manually if needed
    let body = req.body;
    if (typeof body === 'string') {
        try { body = JSON.parse(body); } catch(e) {
            return res.status(400).json({ error: 'Invalid JSON body' });
        }
    }

    const { accessToken, mood, songs, playlistName } = body || {};

    if (!accessToken) return res.status(401).json({ error: 'No Spotify access token provided' });
    if (!songs?.length) return res.status(400).json({ error: 'No songs to export' });

    const spotifyHeaders = {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type':  'application/json'
    };

    try {
        // Step 1 — Get user Spotify ID
        const profileResp = await fetch('https://api.spotify.com/v1/me', { headers: spotifyHeaders });
        const profile     = await profileResp.json();

        if (!profile.id) {
            return res.status(401).json({ error: 'Invalid or expired Spotify token. Please reconnect.' });
        }

        // Step 2 — Create playlist
        const name       = playlistName || `${MOOD_EMOJIS[mood] || '🎵'} ${mood ? mood.charAt(0).toUpperCase() + mood.slice(1) : 'My'} Playlist — TuneItIn`;
        const desc       = `Generated by TuneItIn · tuneitin.app · ${new Date().toLocaleDateString()}`;

        const createResp = await fetch(`https://api.spotify.com/v1/users/${profile.id}/playlists`, {
            method:  'POST',
            headers: spotifyHeaders,
            body:    JSON.stringify({ name, description: desc, public: false })
        });
        const playlist = await createResp.json();

        if (!playlist.id) {
            return res.status(500).json({ error: 'Failed to create playlist on Spotify' });
        }

        // Step 3 — Find Spotify track IDs
        const uriResults = await Promise.allSettled(
            songs.map(async song => {
                if (song.spotifyId) return `spotify:track:${song.spotifyId}`;

                const q          = encodeURIComponent(`track:"${song.name}" artist:"${song.artist}"`);
                const searchResp = await fetch(
                    `https://api.spotify.com/v1/search?q=${q}&type=track&limit=1`,
                    { headers: spotifyHeaders }
                );
                const searchData = await searchResp.json();
                const id         = searchData?.tracks?.items?.[0]?.id;
                return id ? `spotify:track:${id}` : null;
            })
        );

        const uris = uriResults
            .filter(r => r.status === 'fulfilled' && r.value)
            .map(r => r.value);

        if (!uris.length) {
            return res.status(400).json({ error: 'Could not find any of these songs on Spotify' });
        }

        // Step 4 — Add tracks to playlist
        for (let i = 0; i < uris.length; i += 100) {
            await fetch(`https://api.spotify.com/v1/playlists/${playlist.id}/tracks`, {
                method:  'POST',
                headers: spotifyHeaders,
                body:    JSON.stringify({ uris: uris.slice(i, i + 100) })
            });
        }

        return res.status(200).json({
            success:      true,
            playlistId:   playlist.id,
            playlistUrl:  playlist.external_urls?.spotify,
            playlistName: name,
            tracksAdded:  uris.length
        });

    } catch(err) {
        console.error('Export error:', err);
        return res.status(500).json({ error: err.message || 'Something went wrong. Please try again.' });
    }
}
